export enum MintEnum {
	SUCCESS = "SUCCESS",
	ERROR = "ERROR",
	LOADING = "LOADING"
}

export enum MintStatusEnum {
	MINT_DISABLED = "MINT_DISABLED",
	MINT_START = "MINT_START",
	WHITE_LIST_MINT = "WHITE_LIST_MINT"
}
